### ISSUE TITLE
FEE

### ISSUE THREAD

**Issue by r-a-y** [cuny-academic-commons/social-paper#10]
I've created this issue just to track what we are doing with FEE.

In commit 5635e64, we are now relying on the wp.org version of FEE:
https://wordpress.org/plugins/wp-front-end-editor/

If we need to make changes to FEE for whatever reason, mods should be made in the `CACSP_FEE` class:
https://github.com/cuny-academic-commons/social-paper/blob/master/includes/class-cacsp-fee.php

`CACSP_FEE` extends the main `FEE` class so we should be able to make any overrides there.  I believe I've ported all the changes that we previously made to our bundled version of FEE:
https://github.com/cuny-academic-commons/social-paper/commits/master/lib/wp-front-end-editor

@christianwach - I also have a question about the "Tags" button in FEE, but I'll reply in this thread:
https://github.com/cuny-academic-commons/social-paper/commit/789aa14c59d6f4b65e633c99cb99c1c4769bdd6f

If anyone has any questions, let me know.

---

**Todos:**
- [ ] FEE needs to be manually bumped to support WP 4.3.1 (needs to be fixed upstream) - see https://github.com/iseulde/wp-front-end-editor/issues/257
- [ ] Floating toolbar doesn't show up in FEE when attempting to edit an "Add a block" item or when selecting some text (see temp. fix here - https://github.com/iseulde/wp-front-end-editor/pull/261/files)
- [ ] Clicking on the "X" button multiple times in the floating image toolbar removes parent elements (see temp. fix here - https://github.com/iseulde/wp-front-end-editor/pull/267/files)

**Comment by rjbaniel** [comment]
So I've taken FEE out of our code, and then added compatibility via functions.php: https://github.com/cuny-academic-commons/social-paper/commit/740ba0dcb41d61f0da595fc25a4574cdd1d9c9d8

**Comment by rjbaniel** [comment]
I also had a question about the styling on the edit button - for me adding in the extra relative positioning made the Edit button look strange with the rest of the Admin bar. Is that true for you all, too?

**Comment by r-a-y** [comment]
> I also had a question about the styling on the edit button - for me adding in the extra relative positioning made the Edit button look strange with the rest of the Admin bar. Is that true for you all, too?

Can you post a screenshot, Dan?

At the moment, the admin bar shouldn't be displayed on a Social Paper page.

Here's what it should look like:
![Screenshot of a Social Paper page](https://cloud.githubusercontent.com/assets/505921/8917296/0987f78c-3466-11e5-90e9-32c9083e2ae5.gif)

The styling of the "Enable Editing" button could use more work.  It's temporary until we hand off the UX to the rest of the team later on.  We might also bring back a version of the admin bar pending feedback as well.

**Comment by rjbaniel** [comment]
That's weird! Yeah I'm on master and I can see that admin-bar is being enqueued in cacsp_asset_enqueue_handler(), and the whole admin bar is showing, which seems to be covering up the button you added. And since the admin bar is visible, the "Edit Paper" button is to, but it's just positioned weirdly because of the extra styling. What do you think I'm missing here?

Also, took my first shot at adding admin notices to check for FEE here: https://github.com/cuny-academic-commons/social-paper/commit/8cd8e0e2dab988e411d4bdbbb13131302def405d

**Comment by r-a-y** [comment]
> I can see that admin-bar is being enqueued in cacsp_asset_enqueue_handler()

Good catch!  I've removed the two admin bar enqueues in commit ecebb2d.

> and the whole admin bar is showing, which seems to be covering up the button you added

Hmm... maybe `_cacsp_disable_admin_bar_on_social_paper_pages()` is not working as intended.  It's already firing at priority 1, which is pretty early.  Maybe play around with the priority of the `'admin_bar_init'` hook on your install and see if it works?

Update: I've moved the disable admin bar code to the 'wp' hook in commit 125dd06.  Let me know if that works.

**Comment by r-a-y** [comment]
So in WordPress 4.3, FEE's floating toolbar doesn't show up when attempting to edit an "Add a block" item or when selecting some text.

I've hacked FEE's JS to temporarily fix this:
https://github.com/iseulde/wp-front-end-editor/pull/261/files

I'll be patching this on cdev just so our testers will have something to work with, but this needs a bit more work since the toolbar fades in and out when a button is clicked in the floating toolbar.

**Comment by r-a-y** [comment]
Found another issue - if the floating image toolbar is visible and you click on the "X" button multiple times, this will remove parent elements from view.

![GIF](https://cloud.githubusercontent.com/assets/505921/10291760/5db5b3f4-6b60-11e5-8d33-49db051dedec.gif)

I have a fix for this and have added a PR for FEE here:
https://github.com/iseulde/wp-front-end-editor/pull/267/files
