### ISSUE TITLE
Support the WA Fronted editor plugin

### ISSUE THREAD

**Issue by r-a-y** [cuny-academic-commons/social-paper#41]
When we started developing Social Paper, only FEE was a viable option for a frontend editor.

WA-Fronted is another frontend editor plugin that has more momentum behind it, appears to be less buggy and is in active development:
https://github.com/jesperbjerke/wa-fronted

It has revision history support, which is on our roadmap and will probably fix many issues that we have with FEE including #10 and #30.

Some of our JS will need to be modified to support WA Fronted.  Most notably, the sidebar settings toggle and comment auto-positioning code (see commit 39a83fc).

Marking this as a future release, perhaps as a v2.0.

**Notes:**
- WA Fronted does not have a toggle for enabling editing.  When you land on your paper page, you can edit immediately.
- ~~Unlike FEE, saving a post in WA will reload the entire page~~.  As of WA v1.3.0, this is no longer the case.

**Todo:**
- [ ] Support our custom sidebar from FEE.
- [ ] "New Paper" page needs to be adjusted to work with WA Fronted.
- [ ] Will probably need to add a "Show Comments" toggle since WA doesn't have an 'Enable Editing' button.
- [x] Stripping the `data-incom` attribute by Inline Comments will need some work since WA doesn't have a `before-save` JS hook. (doing this at the server level for now - see commit 9b66cb5)

**Comment by boonebgorges** [comment]
This looks really promising - thanks, @r-a-y!

One lame side note is that the plugin requires PHP 5.4.3, a requirement 
we don't meet on the Commons production server. We (desparately) need to 
upgrade anyway, so maybe it's no big deal, but it's one more thing to do.
